name: Build
on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-10.15, windows-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
  
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.15.0
  
      - name: Install Dependencies
        run: |
          npm install
  
      - name: Build Electron App
        run: |
          npm run dist -- --mac
