name: Release
on:
  push:
    branches:
      - releases/*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-12]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
  
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.15.0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  
      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for Windows
        if: matrix.os == 'windows-latest'
        run: npm run electron-builder build --win portable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Electron App for macOS
        if: matrix.os == 'macos-12'
        run: npm run electron-builder build --mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List build directory
        run: ls -l ./dist

      - name: Create Release
        if: startsWith(github.ref, 'refs/heads/releases/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Windows Asset
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/TimeTrack.exe
          asset_name: TimeTrack.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload macOS Asset
        if: matrix.os == 'macos-12'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/TimeTrack.dmg
          asset_name: TimeTrack.dmg
          asset_content_type: application/x-dmg
